### PR TITLE
Add missing required param to README

### PR DESCRIPTION
**Pull request by szepeviktor**
https://github.com/dtolnay/rust-toolchain/blob/be73d7920c329f220ce78e0234b8f96b7ae60248/action.yml#L9-L11

### CODE REVIEW

**Comment by andrey-yantsen** [comment]
@szepeviktor you don't need to specify the toolchain if you use a "smart" tag: https://github.com/dtolnay/rust-toolchain/blob/78c6b5541adb5849f5d72d15da722aedb26327ca/README.md?plain=1#L24-L27

The `toolchain` param needs to be provided only if you use `master` as the `@rev`.

**Comment by szepeviktor** [comment]
@andrey-yantsen Thank you. I thought it is required:

https://github.com/dtolnay/rust-toolchain/blob/be73d7920c329f220ce78e0234b8f96b7ae60248/action.yml#L9-L11

**Comment by andrey-yantsen** [comment]
Yeah, I understand where you're coming from. But magic is all around us! I don't know how else to describe what happens in other branches :) https://github.com/dtolnay/rust-toolchain/blob/78c6b5541adb5849f5d72d15da722aedb26327ca/action.yml#L9-L12

**Comment by dtolnay** [comment]
That's right, the branches other than dtolnay/rust-toolchain@master do not require `toolchain`.

**Pull request closed without merging**
